### ISSUE TITLE
 Week-1 Study resource for Asynchronous

### ISSUE THREAD

**Issue by sultanien** [HackYourFuture/UsingAPIs#4]
In https://hackyourfuture.github.io/study/#/javascript/asynchronous the first link for [Asynchronous JavaScript](https://www.youtube.com/watch?v=YxWMxJONp7E) could be updated with https://www.youtube.com/watch?v=ZcQyJ-gxke0&list=PL4cUxeGkcC9jx2TTZk3IGWKSbtugYdrlu. It is updated version of it.

**Comment by robvk** [comment]
Fixed, thanks
